import psycopg2
conn = psycopg2.connect('postgresql://postgres:MaEHyMeUBqdeBJdrTWodZJEKoQcldCEN@centerbeam.proxy.rlwy.net:47825/railway')
cur = conn.cursor()
cur.execute('SELECT COUNT(*), MIN(created_at), MAX(created_at) FROM trade_outcomes')
print('total/min/max:', cur.fetchone())
cur.execute('SELECT direction, COUNT(*), SUM(CASE WHEN was_win THEN 1 ELSE 0 END) FROM trade_outcomes GROUP BY direction ORDER BY 2 DESC')
print('by direction:', cur.fetchall())
cur.execute('SELECT asset, timeframe, COUNT(*) FROM trade_outcomes GROUP BY 1,2 ORDER BY 3 DESC')
print('by asset/tf:', cur.fetchall())
cur.execute('SELECT COUNT(*) FROM pending_trades')
print('pending:', cur.fetchone())
cur.execute('SELECT COUNT(*), AVG(LENGTH(features_json)) FROM trade_outcomes WHERE features_json IS NOT NULL AND features_json<>\'\'')
print('with features/avg len:', cur.fetchone())
cur.execute('SELECT date_trunc(\'hour\', created_at), COUNT(*) FROM trade_outcomes GROUP BY 1 ORDER BY 1 DESC LIMIT 12')
print('per hour:', cur.fetchall())
cur.execute('SELECT MAX(open_time) FROM subminute_candles')
print('last subminute:', cur.fetchone())
cur.execute('SELECT MAX(open_time) FROM historical_candles')
print('last hist:', cur.fetchone())
