using Prometheus;

namespace ValutaBot.MiniApp;

/// <summary>
/// Domain metrics collected and exposed for Prometheus / Grafana observability.
/// </summary>
public static class ValutaMetrics
{
    public static readonly Counter PredictionsTotal = Metrics.CreateCounter(
        "valutabot_predictions_total",
        "Total number of trading predictions generated by the bot",
        new CounterConfiguration
        {
            LabelNames = new[] { "asset", "timeframe", "direction", "model_version" }
        });

    public static readonly Histogram PipelineDuration = Metrics.CreateHistogram(
        "valutabot_pipeline_duration_seconds",
        "Duration of the market analysis pipeline in seconds",
        new HistogramConfiguration
        {
            Buckets = new[] { 0.025, 0.05, 0.1, 0.2, 0.4, 0.8, 1.5, 3.0, 6.0 }
        });

    public static readonly Counter HealthCheckFailures = Metrics.CreateCounter(
        "valutabot_healthcheck_failures_total",
        "Total number of failed health checks",
        new CounterConfiguration
        {
            LabelNames = new[] { "component" }
        });

    public static readonly Counter WebSocketTicksTotal = Metrics.CreateCounter(
        "valutabot_websocket_ticks_total",
        "Total number of live forex ticks ingested via WebSocket stream",
        new CounterConfiguration
        {
            LabelNames = new[] { "symbol" }
        });
}
